# Generated by Django 2.1.7 on 2019-03-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='pics',
            field=models.ManyToManyField(related_name='pic', to='AIM_GAMES.URL'),
        ),
    ]
