# Generated by Django 2.1.7 on 2019-03-27 14:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastPayment', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.TextField(max_length=50)),
                ('formation', models.TextField(max_length=100)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('miniature', models.URLField()),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GraphicEngine',
            fields=[
                ('title', models.TextField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GraphicEngineExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphicExperience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Curriculum')),
                ('graphicEngine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.GraphicEngine')),
            ],
        ),
        migrations.CreateModel(
            name='HTML5Showcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedCode', models.TextField()),
                ('curriculum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='HTML5Showcase', to='AIM_GAMES.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField(max_length=100)),
                ('experienceRequired', models.TextField(max_length=100)),
                ('schedule', models.TextField(max_length=100)),
                ('salary', models.IntegerField()),
                ('ubication', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
                ('images', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.TextField(max_length=50)),
                ('formation', models.TextField(max_length=100)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('miniature', models.URLField()),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('surname', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.TextField(max_length=30)),
                ('postalCode', models.TextField(max_length=16)),
                ('idCardNumber', models.TextField(max_length=10)),
                ('dateOfBirth', models.DateTimeField()),
                ('phoneNumber', models.TextField(max_length=20)),
                ('photo', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('title', models.TextField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Valoration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Business')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Thread')),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='attachedFiles',
            field=models.ManyToManyField(related_name='attachedFile', to='AIM_GAMES.URL'),
        ),
        migrations.AddField(
            model_name='thread',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Business'),
        ),
        migrations.AddField(
            model_name='thread',
            name='pics',
            field=models.ManyToManyField(related_name='pic', to='AIM_GAMES.URL'),
        ),
        migrations.AddField(
            model_name='thread',
            name='tags',
            field=models.ManyToManyField(to='AIM_GAMES.Tag'),
        ),
        migrations.AddField(
            model_name='response',
            name='pics',
            field=models.ManyToManyField(to='AIM_GAMES.URL'),
        ),
        migrations.AddField(
            model_name='response',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Thread'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Profile'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='freelancer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Freelancer'),
        ),
        migrations.AddField(
            model_name='business',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Profile'),
        ),
        migrations.AddField(
            model_name='aptitude',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Curriculum'),
        ),
        migrations.AlterUniqueTogether(
            name='valoration',
            unique_together={('thread', 'business')},
        ),
    ]
