# Generated by Django 2.1.7 on 2019-04-08 23:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aptitude', models.TextField(default='defaul', max_length=30, verbose_name='aptitude')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastPayment', models.DateTimeField(null=True, verbose_name='lastPayment')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('objectives', models.TextField(verbose_name='objectives')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Business', verbose_name='business')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Challenge', verbose_name='challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(verbose_name='location')),
                ('title', models.TextField(max_length=150, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('moment', models.DateTimeField()),
                ('companies', models.ManyToManyField(to='AIM_GAMES.Business', verbose_name='companies')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.TextField(max_length=50, verbose_name='center')),
                ('formation', models.TextField(max_length=100, verbose_name='formation')),
                ('startDate', models.DateTimeField(verbose_name='startDate')),
                ('endDate', models.DateTimeField(verbose_name='endDate')),
                ('miniature', models.URLField(verbose_name='miniature')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Curriculum', verbose_name='curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.TextField(max_length=100, verbose_name='profession')),
            ],
        ),
        migrations.CreateModel(
            name='GraphicEngine',
            fields=[
                ('title', models.TextField(max_length=50, primary_key=True, serialize=False, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='GraphicEngineExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphicExperience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='graphicExperience')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Curriculum', verbose_name='curriculum')),
                ('graphicEngine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.GraphicEngine', verbose_name='graphicEngine')),
            ],
        ),
        migrations.CreateModel(
            name='HTML5Showcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedCode', models.TextField(verbose_name='embedCode')),
                ('curriculum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='HTML5Showcase', to='AIM_GAMES.Curriculum', verbose_name='curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField(max_length=100, verbose_name='position')),
                ('experienceRequired', models.TextField(max_length=100, verbose_name='experienceRequired')),
                ('schedule', models.TextField(max_length=100, verbose_name='schedule')),
                ('salary', models.IntegerField(verbose_name='salary')),
                ('ubication', models.TextField(max_length=100, verbose_name='ubication')),
                ('description', models.TextField(max_length=10000, verbose_name='description')),
                ('images', models.TextField(verbose_name='images')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Business', verbose_name='business')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='url')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Curriculum', verbose_name='curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=100)),
                ('text', models.TextField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_messages', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.TextField(max_length=50, verbose_name='center')),
                ('formation', models.TextField(max_length=100, verbose_name='formation')),
                ('startDate', models.DateTimeField(verbose_name='startDate')),
                ('endDate', models.DateTimeField(verbose_name='endDate')),
                ('miniature', models.URLField(verbose_name='miniature')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Curriculum', verbose_name='curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, verbose_name='name')),
                ('surname', models.TextField(max_length=50, verbose_name='surname')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('city', models.TextField(max_length=30, verbose_name='city')),
                ('postalCode', models.TextField(max_length=16, verbose_name='Postal Code')),
                ('idCardNumber', models.TextField(max_length=10, verbose_name='IDCard Number')),
                ('dateOfBirth', models.DateTimeField(verbose_name='Date of birth')),
                ('phoneNumber', models.TextField(max_length=20, verbose_name='Phone number')),
                ('photo', models.URLField(verbose_name='Photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Business', verbose_name='business')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('title', models.TextField(max_length=20, primary_key=True, serialize=False, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(default='http://default.com', verbose_name='uri')),
            ],
        ),
        migrations.CreateModel(
            name='Valoration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='score')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Business', verbose_name='business')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Thread', verbose_name='thread')),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='attachedFiles',
            field=models.ManyToManyField(related_name='attachedFile', to='AIM_GAMES.URL', verbose_name='attachedFiles'),
        ),
        migrations.AddField(
            model_name='thread',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Business', verbose_name='business'),
        ),
        migrations.AddField(
            model_name='thread',
            name='pics',
            field=models.ManyToManyField(related_name='pic', to='AIM_GAMES.URL', verbose_name='pics'),
        ),
        migrations.AddField(
            model_name='thread',
            name='tags',
            field=models.ManyToManyField(blank=True, to='AIM_GAMES.Tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='response',
            name='pics',
            field=models.ManyToManyField(to='AIM_GAMES.URL', verbose_name='pics'),
        ),
        migrations.AddField(
            model_name='response',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Thread', verbose_name='thread'),
        ),
        migrations.AddField(
            model_name='manager',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Profile', verbose_name='profile'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Profile', verbose_name='profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='freelancers',
            field=models.ManyToManyField(to='AIM_GAMES.Freelancer', verbose_name='freelancers'),
        ),
        migrations.AddField(
            model_name='event',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Manager', verbose_name='manager'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='freelancer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Freelancer', verbose_name='freelancer'),
        ),
        migrations.AddField(
            model_name='challengeresponse',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Freelancer', verbose_name='freelancer'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='freelancers',
            field=models.ManyToManyField(to='AIM_GAMES.Freelancer', verbose_name='freelancers'),
        ),
        migrations.AddField(
            model_name='business',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Profile', verbose_name='profile'),
        ),
        migrations.AddField(
            model_name='aptitude',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Curriculum', verbose_name='curriculum'),
        ),
        migrations.AlterUniqueTogether(
            name='valoration',
            unique_together={('thread', 'business')},
        ),
    ]
