# Generated by Django 2.1.7 on 2019-03-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='center',
            field=models.TextField(max_length=50, verbose_name='Centro'),
        ),
    ]
