# Generated by Django 2.1.7 on 2019-03-26 15:22

from __future__ import unicode_literals
from django.db import models, migrations

def load_tag(apps, schema_editor):
    Tag = apps.get_model("AIM_GAMES", "Tag")
    tag1 = Tag(title='tag1')
    tag1.save()
    tag2 = Tag(title='tag2')
    tag2.save()
    tag3 = Tag(title='tag3')
    tag3.save()

def load_url(apps, schema_editor):
    URL = apps.get_model("AIM_GAMES", "URL")
    url1 = URL(title='http://www.funcage.com/blog/wp-content/uploads/2013/11/Random-Photoshopped-Pictures-006.jpg')
    url1.save()
    url2 = URL(title='http://www.funcage.com/blog/wp-content/uploads/2013/11/Random-Photoshopped-Pictures-006.jpg')
    url2.save()
    url3 = URL(title='http://www.funcage.com/blog/wp-content/uploads/2013/11/Random-Photoshopped-Pictures-006.jpg')
    url3.save()



class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_tag),
        migrations.RunPython(load_url),
    ]
