# Generated by Django 2.1.7 on 2019-03-25 16:08

from django.db import migrations, models
from django.contrib.auth.models import Group, Permission

def add_group_permissions():
    group, created = Group.objects.get_or_create(name='Business')
    if created:
        can_add_job_offer = Permission.objects.get(name='Can add job offer')
        group.permissions.add(can_add_job_offer)

    group, created = Group.objects.get_or_create(name='Freelancer') 
   

class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0002_business_lastpayment'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
