# Generated by Django 2.1.7 on 2019-03-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0002_auto_20190316_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='procession',
            new_name='profession',
        ),
    ]
