# Generated by Django 2.1.7 on 2019-03-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0002_auto_20190327_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperience',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
