# Generated by Django 2.1.7 on 2019-03-25 16:08

from django.db import migrations, models
from django.contrib.auth.models import Group


def add_group_permissions():
    #Business
    group, created = Group.objects.get_or_create(name='Business')   


    #Freelancer
    group, created = Group.objects.get_or_create(name='Freelancer') 




class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0002_business_lastpayment'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
