# Generated by Django 2.1.7 on 2019-03-25 16:08

from django.db import migrations, models
from django.contrib.auth.models import Group

def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=u'Freelancer'),
        Group(name=u'Business')
    ])


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            u'Freelancer',
            u'Business',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0002_business_lastpayment'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
