# Generated by Django 2.1.7 on 2019-03-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0003_auto_20190326_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html5showcase',
            name='curriculum',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='HTML5Showcase', to='AIM_GAMES.Curriculum'),
        ),
    ]
