# Generated by Django 2.1.7 on 2019-03-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0004_auto_20190329_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='center',
            field=models.TextField(help_text='Centroooo', max_length=50, verbose_name='Centrooo'),
        ),
    ]
