# Generated by Django 2.1.7 on 2019-04-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0006_auto_20190401_2320'),
        ('AIM_GAMES', '0006_auto_20190401_2146'),
    ]

    operations = [
    ]
