# Generated by Django 2.1.7 on 2019-04-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0007_merge_20190402_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='title',
        ),
        migrations.AddField(
            model_name='url',
            name='uri',
            field=models.URLField(default='http://default.com', verbose_name='uri'),
        ),
    ]
