# Generated by Django 2.1.7 on 2019-04-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0008_auto_20190402_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aptitude',
            name='title',
        ),
        migrations.AddField(
            model_name='aptitude',
            name='aptitude',
            field=models.TextField(default='defaul', max_length=30, verbose_name='aptitude'),
        ),
    ]
