# Generated by Django 2.1.7 on 2019-04-08 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIM_GAMES', '0009_auto_20190402_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Challenge', verbose_name='challenge')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIM_GAMES.Freelancer', verbose_name='freelancer')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.TextField(max_length=150, verbose_name='title'),
        ),
    ]
